#!/usr/bin/env bash

set -e

echo "✨ Installing MathTools AI Development Framework Installer (mathtools)..."

# Check requirements
if ! command -v git &> /dev/null; then
    echo "❌ Error: git is required but not installed."
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "❌ Error: python3 is required but not installed."
    exit 1
fi

INSTALL_DIR="$HOME/.local/share/mathtools"
BIN_DIR="$HOME/.local/bin"
REPO_URL="https://github.com/matrueba/mathtools.git"

echo "📦 Setting up repository in $INSTALL_DIR..."
# 1. Clone or update repository
if [ -d "$INSTALL_DIR/.git" ]; then
    echo "   Updating existing installation..."
    cd "$INSTALL_DIR"
    git pull origin main --quiet
elif [ -d "$INSTALL_DIR" ]; then
    echo "   Existing directory $INSTALL_DIR is not a git repository. Re-cloning..."
    rm -rf "$INSTALL_DIR"
    git clone --quiet "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
else
    echo "   Cloning from GitHub..."
    git clone --quiet "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# 2. Setup Virtual Environment
echo "🐍 Setting up Python virtual environment..."
python3 -m venv .venv
source .venv/bin/activate

# 3. Install dependencies
echo "⚙️  Installing package and dependencies..."
pip install -q -e .

# 4. Create wrapper in ~/.local/bin
echo "🔗 Creating global command 'mathtools'..."
mkdir -p "$BIN_DIR"

# Create a symlink to the script generated by pip in the virtual env
ln -sf "$INSTALL_DIR/.venv/bin/mathtools" "$BIN_DIR/mathtools"

echo ""
echo "✅ Installation completed successfully!"

# Check if ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo "⚠️  WARNING: $BIN_DIR is not in your PATH."
    echo "To be able to run the command from anywhere, please add the following line to your ~/.bashrc or ~/.zshrc:"
    echo "    export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
    echo "Then restart your terminal or run: source ~/.bashrc"
    echo "You can still run the CLI directly using: $BIN_DIR/mathtools"
else
    echo "Run 'mathtools' in your terminal to get started."
fi
